export const SEARCH_DATA_REQUEST = 'SEARCH_DATA_REQUEST';
export const SEARCH_DATA_RESPONSE = 'SEARCH_DATA_RESPONSE';
export const SEARCH_DATA_ERROR = 'SEARCH_DATA_ERROR';
export const SET_MAP_OPTIONS = 'SET_MAP_OPTIONS';
export const TOGGLE_SEARCH_AREA = 'TOGGLE_SEARCH_AREA';
